### ISSUE TITLE
can't install batstat

### ISSUE THREAD

**Issue by PegHorse** [Juve45/batstat#10]
Hi,

I'm trying to install but it doesn't work

![image](https://user-images.githubusercontent.com/7678316/221358028-96dc60e4-b3c5-4182-b41b-7ce30a17c036.png)
![image](https://user-images.githubusercontent.com/7678316/221358064-7f955f88-73a7-4989-9b0f-028338f281f2.png)

**Make install doesn't work too while i have the dependencies**

![image](https://user-images.githubusercontent.com/7678316/221358248-b7b3cc80-2442-458a-8520-2c805cc3a35c.png)

**Comment by Kentajoh** [comment]
Same. Fedora 37

**Comment by gingercookies** [comment]
> Hi,
> 
> I'm trying to install but it doesn't work
> 
> ![image](https://user-images.githubusercontent.com/7678316/221358028-96dc60e4-b3c5-4182-b41b-7ce30a17c036.png) ![image](https://user-images.githubusercontent.com/7678316/221358064-7f955f88-73a7-4989-9b0f-028338f281f2.png)
> 
> **Make install doesn't work too while i have the dependencies**
> 
> ![image](https://user-images.githubusercontent.com/7678316/221358248-b7b3cc80-2442-458a-8520-2c805cc3a35c.png)

Apparently, you need to build batstat to install itself :V
My way to install is:
-  sudo apt-get install make g++ libncurses5-dev
-  sudo make build
-  sudo make install

(Make sure that you do all of this inside batstat folder)

**Comment by Juve45** [comment]
updated readme to include commands to compile batstat
