### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by codyro** [Juve45/batstat#12]
Hello,

What license is this code/software available under? If you haven't chosen one, you might find the following resources helpful:

* https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license
* https://choosealicense.com/

A useful tidbit: 

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by codyro** [comment]
Bump :)

**Comment by Juve45** [comment]
finally added :)

**Comment by codyro** [comment]
Thank you!

**Comment by carlwgeorge** [comment]
Now that this project has a license, would it be possible to add a tag to "release" an initial version?

**Comment by Juve45** [comment]
Also added a release version! Thanks for suggestions :)
