### ISSUE TITLE
Please add some options to let user modify the battery info path

### ISSUE THREAD

**Issue by Ryan0604** [Juve45/batstat#3]
it doesn't work on Centos7.6.1810 because of the different path...

**Comment by pakair** [comment]
I guess you can modify the #define PATH "the path" in the code & recompile.

**Comment by Juve45** [comment]
I did not found anything regarding the path of battery files on CentOS, at the moment the only place the app looks for the battery files is `/sys/class/power_supply/BAT0` or `/sys/class/power_supply/BAT1`

**Comment by Juve45** [comment]
Added config file
