### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by maravento** [Juve45/batstat#9]
```
~/batstat$ sudo make install
install -m 775 batstat /usr/local/bin
install: cannot perform `stat' on 'batstat': No such file or directory
make: *** [Makefile:21: install] Error 1
```
[this method](https://www.linuxjournal.com/content/how-check-battery-status-using-linux-command-line) or [this one](https://ostechnix.com/how-to-check-laptop-battery-status-in-terminal-in-linux/#:~:text=Method%204%3A%20Using%20%22Batstat%22%20Program) don't work either

how to install (preferably ubuntu 22.04)? thanks

**Comment by sayaaep** [comment]
first sudo make then sudo make install 
read readme.md
